# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('template_version', models.CharField(default='v1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / Generated'), ('SUPERSEDED', 'Superseded'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('agreement_data', models.JSONField(default=dict)),
                ('pdf_storage_key', models.CharField(blank=True, max_length=1000)),
                ('docx_storage_key', models.CharField(blank=True, max_length=1000)),
                ('document_hash', models.CharField(blank=True, max_length=128)),
                ('docx_hash', models.CharField(blank=True, max_length=128)),
                ('version_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='loans.loan')),
                ('parent_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='agreements.loanagreement')),
            ],
            options={
                'db_table': 'agreements_loanagreement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agreement_number'], name='agreements__agreeme_8915e4_idx'), models.Index(fields=['loan', 'status'], name='agreements__loan_id_1131f6_idx')],
            },
        ),
    ]
