# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('pan_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENT_REQUIRED', 'Document Required'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Reverification Required')], default='NOT_STARTED', max_length=20)),
                ('aadhaar_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENT_REQUIRED', 'Document Required'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Reverification Required')], default='NOT_STARTED', max_length=20)),
                ('address_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENT_REQUIRED', 'Document Required'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Reverification Required')], default='NOT_STARTED', max_length=20)),
                ('identity_match_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENT_REQUIRED', 'Document Required'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Reverification Required')], default='NOT_STARTED', max_length=20)),
                ('overall_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENT_REQUIRED', 'Document Required'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Reverification Required')], default='NOT_STARTED', max_length=25)),
                ('admin_approved', models.BooleanField(default=False)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_approvals', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_profile', to='borrowers.borrower')),
            ],
            options={
                'db_table': 'kyc_profile',
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('PAN', 'PAN Verification'), ('AADHAAR', 'Aadhaar / e-KYC'), ('MOBILE', 'Mobile OTP'), ('EMAIL', 'Email OTP'), ('DOCUMENT', 'Document Verification')], max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('OTP_SENT', 'OTP Sent'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='INITIATED', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_text', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_reference_id', models.CharField(blank=True, max_length=200)),
                ('provider_request_id', models.CharField(blank=True, max_length=200)),
                ('name_match', models.BooleanField(blank=True, null=True)),
                ('dob_match', models.BooleanField(blank=True, null=True)),
                ('address_match', models.BooleanField(blank=True, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='kyc.kycprofile')),
            ],
            options={
                'db_table': 'kyc_verification',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['verification_type', 'status'], name='kyc_verific_verific_9cc6ae_idx'), models.Index(fields=['kyc_profile'], name='kyc_verific_kyc_pro_be2a8d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['overall_status'], name='kyc_profile_overall_6197d4_idx'),
        ),
    ]
