# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_no', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='UPCOMING', max_length=20)),
                ('waiver_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_schedule', to='loans.loan')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_installments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_schedule',
                'ordering': ['installment_no'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('OTHER', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentschedule')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['due_date'], name='payments_sc_due_dat_a9d5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['status'], name='payments_sc_status_a9ebda_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['loan', 'status'], name='payments_sc_loan_id_431a4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together={('loan', 'installment_no')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='payments_pa_transac_2dc1cb_idx'),
        ),
    ]
