# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('ADDRESS_PROOF', 'Address Proof'), ('BANK_PROOF', 'Bank Proof'), ('PHOTOGRAPH', 'Photograph'), ('SIGNATURE', 'Signature'), ('INCOME_PROOF', 'Income Proof'), ('OTHER', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=500)),
                ('storage_key', models.CharField(max_length=1000)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='borrowers.borrower')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['borrower', 'document_type'], name='documents_d_borrowe_1552df_idx'), models.Index(fields=['verification_status'], name='documents_d_verific_9ea278_idx'), models.Index(fields=['is_current'], name='documents_d_is_curr_fe24da_idx')],
            },
        ),
    ]
