# Generated by Django 4.2.30 on 2026-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('PAN_FRONT', 'PAN Card Front'), ('PAN_BACK', 'PAN Card Back'), ('AADHAAR', 'Aadhaar Card'), ('AADHAAR_FRONT', 'Aadhaar Card Front'), ('AADHAAR_BACK', 'Aadhaar Card Back'), ('BANK_STATEMENT', 'Bank Statement'), ('BANK_PASSBOOK', 'Bank Passbook'), ('ADDRESS_PROOF', 'Address Proof'), ('BANK_PROOF', 'Bank Proof'), ('PHOTOGRAPH', 'Photograph'), ('SIGNATURE', 'Signature'), ('INCOME_PROOF', 'Income Proof'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
