# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lenders', '0001_initial'),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('interest_method', models.CharField(choices=[('FLAT_RATE', 'Flat Rate (P × R × T)'), ('REDUCING_BALANCE', 'Reducing Balance (EMI)')], default='REDUCING_BALANCE', max_length=20)),
                ('repayment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('FORTNIGHTLY', 'Fortnightly')], default='WEEKLY', max_length=15)),
                ('number_of_installments', models.PositiveSmallIntegerField(default=25)),
                ('loan_start_date', models.DateField()),
                ('first_payment_date', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled'), ('PENDING_APPROVAL', 'Pending Approval')], default='DRAFT', max_length=20)),
                ('kyc_exception_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='borrowers.borrower')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('kyc_exception_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_exceptions', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='lenders.lender')),
            ],
            options={
                'db_table': 'loans_loan',
            },
        ),
        migrations.CreateModel(
            name='LoanCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('periodic_interest_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('number_of_installments', models.PositiveSmallIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interest_method', models.CharField(max_length=20)),
                ('amortization_schedule', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('recalculated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='loans.loan')),
            ],
            options={
                'db_table': 'loans_calculation',
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_number'], name='loans_loan_loan_nu_9c0f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_loan_borrowe_d07c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_start_date'], name='loans_loan_loan_st_45706c_idx'),
        ),
    ]
