# Generated by Django 4.2.30 on 2026-08-22 04:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('93.69'), max_digits=6),
        ),
    ]
