# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=50)),
                ('pan_number', models.CharField(blank=True, db_index=True, max_length=10)),
                ('pan_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('pan_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='borrowers/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_borrowers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borrowers_borrower',
                'indexes': [models.Index(fields=['borrower_id'], name='borrowers_b_borrowe_4a7fab_idx'), models.Index(fields=['mobile'], name='borrowers_b_mobile_7a9f3a_idx'), models.Index(fields=['email'], name='borrowers_b_email_0f1546_idx'), models.Index(fields=['pan_hash'], name='borrowers_b_pan_has_15397a_idx'), models.Index(fields=['status'], name='borrowers_b_status_befed1_idx')],
            },
        ),
    ]
