# Generated by Django 4.2.30 on 2026-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='aadhaar_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='borrower',
            name='aadhaar_number',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='borrower',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['aadhaar_hash'], name='borrowers_b_aadhaar_57c9b7_idx'),
        ),
    ]
