# Generated by Django 4.2.30 on 2026-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_VIEW', 'Profile Viewed'), ('PROFILE_UPDATE', 'Profile Updated'), ('KYC_INITIATED', 'KYC Initiated'), ('KYC_PAN_SUBMITTED', 'PAN Submitted'), ('KYC_PAN_VERIFIED', 'PAN Verified'), ('KYC_AADHAAR_CONSENT', 'Aadhaar Consent Given'), ('KYC_AADHAAR_OTP', 'Aadhaar OTP Sent'), ('KYC_AADHAAR_VERIFIED', 'Aadhaar Verified'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_REVERIFICATION', 'KYC Reverification Requested'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_VIEW', 'Document Viewed'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('LOAN_CREATED', 'Loan Created'), ('LOAN_UPDATED', 'Loan Updated'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_CALCULATED', 'Loan Calculated'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('PAYMENT_WAIVED', 'Payment Waived'), ('AGREEMENT_GENERATED', 'Agreement Generated'), ('AGREEMENT_DOWNLOADED', 'Agreement Downloaded'), ('AGREEMENT_VERSION', 'Agreement Version Created'), ('ADMIN_ACTION', 'Admin Action'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_REACTIVATED', 'Account Reactivated')], db_index=True, max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_log_action_09d227_idx'), models.Index(fields=['actor', 'timestamp'], name='audit_log_actor_i_e00306_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_log_target__0238a6_idx')],
            },
        ),
    ]
