# Generated by Django 4.2.30 on 2026-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_VIEW', 'Profile Viewed'), ('PROFILE_UPDATE', 'Profile Updated'), ('KYC_INITIATED', 'KYC Initiated'), ('KYC_PAN_SUBMITTED', 'PAN Submitted'), ('KYC_PAN_VERIFIED', 'PAN Verified'), ('KYC_AADHAAR_CONSENT', 'Aadhaar Consent Given'), ('KYC_AADHAAR_OTP', 'Aadhaar OTP Sent'), ('KYC_AADHAAR_VERIFIED', 'Aadhaar Verified'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_REVERIFICATION', 'KYC Reverification Requested'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_VIEW', 'Document Viewed'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('LOAN_CREATED', 'Loan Created'), ('LOAN_UPDATED', 'Loan Updated'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_CALCULATED', 'Loan Calculated'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('PAYMENT_WAIVED', 'Payment Waived'), ('AGREEMENT_GENERATED', 'Agreement Generated'), ('AGREEMENT_DOWNLOADED', 'Agreement Downloaded'), ('AGREEMENT_VERSION', 'Agreement Version Created'), ('ADMIN_ACTION', 'Admin Action'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_REACTIVATED', 'Account Reactivated'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_TOKEN_CREATED', 'Password Reset Token Created'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_TOKEN_EXPIRED', 'Password Reset Token Expired'), ('PASSWORD_RESET_TOKEN_REUSED', 'Password Reset Token Reused')], db_index=True, max_length=30),
        ),
    ]
